//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// Defines values for GetTripYAMLParamsScope.
const (
	Day  GetTripYAMLParamsScope = "day"
	Full GetTripYAMLParamsScope = "full"
)

// Valid indicates whether the value is a known member of the GetTripYAMLParamsScope enum.
func (e GetTripYAMLParamsScope) Valid() bool {
	switch e {
	case Day:
		return true
	case Full:
		return true
	default:
		return false
	}
}

// ChangeOvernightRequest defines model for ChangeOvernightRequest.
type ChangeOvernightRequest struct {
	// AlsoUpdateNextStart If true (default), set day N+1 route start to new_end and keep its mid/end stops
	AlsoUpdateNextStart *bool `json:"also_update_next_start,omitempty"`

	// Day Travel day whose overnight end changes
	Day int `json:"day"`

	// Force Bypass max overnight distance check (ferry/flight days only)
	Force *bool `json:"force,omitempty"`

	// NewEnd Place id for the new overnight end (kebab-case)
	NewEnd string `json:"new_end"`

	// Places Optional catalog create/update; include new_end with title/lat/lon/type when creating
	Places *map[string]map[string]interface{} `json:"places,omitempty"`

	// Title Optional new title for day N
	Title *string `json:"title,omitempty"`
}

// CreateTripRequest defines model for CreateTripRequest.
type CreateTripRequest struct {
	Id   string `json:"id"`
	Yaml string `json:"yaml"`
}

// DayPatch Partial day body (prefer update_day for title/notes alone)
type DayPatch struct {
	Ferry *bool `json:"ferry,omitempty"`
	Hike  *bool `json:"hike,omitempty"`

	// Notes Day narrative; set when the overnight or story changes
	Notes *string `json:"notes,omitempty"`

	// Route Full replacement of that day's route (ordered place refs)
	Route *[]StopRef `json:"route,omitempty"`

	// Stops Full replacement of that day's stops list
	Stops *[]StopRef `json:"stops,omitempty"`
	Title *string    `json:"title,omitempty"`
}

// Health defines model for Health.
type Health struct {
	Status *string `json:"status,omitempty"`
}

// InsertDay defines model for InsertDay.
type InsertDay struct {
	After *int `json:"after,omitempty"`
	Day   *struct {
		Ferry *bool `json:"ferry,omitempty"`
		Hike  *bool `json:"hike,omitempty"`

		// Notes Human-authored; agents should not set unless asked
		Notes *string    `json:"notes,omitempty"`
		Route *[]StopRef `json:"route,omitempty"`
		Stops *[]StopRef `json:"stops,omitempty"`
		Title *string    `json:"title,omitempty"`
	} `json:"day,omitempty"`
}

// MutateResult defines model for MutateResult.
type MutateResult struct {
	BundleError   *string `json:"bundle_error,omitempty"`
	BundleOk      *bool   `json:"bundle_ok,omitempty"`
	Id            *string `json:"id,omitempty"`
	SchemaVersion *int    `json:"schema_version,omitempty"`
	VersionId     *string `json:"version_id,omitempty"`

	// ViewerUrl Signed-in tripmap viewer path /me/trips/{id}/ (Hellō login required)
	ViewerUrl *string `json:"viewer_url,omitempty"`
}

// PlaceFacilities defines model for PlaceFacilities.
type PlaceFacilities struct {
	DrinkingWater *bool `json:"drinking_water,omitempty"`
	Toilets       *bool `json:"toilets,omitempty"`
}

// PlaceInfo Structured enrichment for a place (optional throughout). Does not include title, lat, lon, or type — those belong on the place object itself. Opening hours belong in logistics.opening_hours (not under stats).
type PlaceInfo struct {
	Facilities *PlaceFacilities `json:"facilities,omitempty"`
	Highlights *[]string        `json:"highlights,omitempty"`
	Links      *[]PlaceLink     `json:"links,omitempty"`
	Logistics  *PlaceLogistics  `json:"logistics,omitempty"`
	Source     *PlaceSource     `json:"source,omitempty"`

	// Stats Trail/drive statistics only — not opening hours
	Stats    *PlaceStats `json:"stats,omitempty"`
	Warnings *[]string   `json:"warnings,omitempty"`
}

// PlaceLink defines model for PlaceLink.
type PlaceLink struct {
	Title *string `json:"title,omitempty"`
	Type  string  `json:"type"`
	Url   string  `json:"url"`
}

// PlaceLogistics defines model for PlaceLogistics.
type PlaceLogistics struct {
	BookingRequired *bool `json:"booking_required,omitempty"`

	// OpeningHours Human-readable opening hours (e.g. Daily 10:00–22:30)
	OpeningHours *string `json:"opening_hours,omitempty"`
	Parking      *string `json:"parking,omitempty"`
}

// PlacePatch Partial place catalog upsert (top-level identity fields + optional PlaceInfo)
type PlacePatch struct {
	// Info Structured enrichment for a place (optional throughout). Does not include title, lat, lon, or type — those belong on the place object itself. Opening hours belong in logistics.opening_hours (not under stats).
	Info *PlaceInfo `json:"info,omitempty"`
	Lat  *float32   `json:"lat,omitempty"`
	Lon  *float32   `json:"lon,omitempty"`

	// MapsUrl Google Maps place URL for the viewer pin; when set, overrides lat/lon search
	MapsUrl      *string `json:"maps_url,omitempty"`
	Notes        *string `json:"notes,omitempty"`
	Photo        *string `json:"photo,omitempty"`
	PhotoCaption *string `json:"photo_caption,omitempty"`

	// Title Display name; required on the place for new ids (not under info)
	Title *string `json:"title,omitempty"`

	// Type e.g. overnight, restaurant, attraction, via
	Type *string `json:"type,omitempty"`
}

// PlaceSource defines model for PlaceSource.
type PlaceSource struct {
	GeneratedAt *string `json:"generated_at,omitempty"`
	GeneratedBy *string `json:"generated_by,omitempty"`
}

// PlaceStats Trail/drive statistics only — not opening hours
type PlaceStats struct {
	AscentM    *float32 `json:"ascent_m,omitempty"`
	Difficulty *string  `json:"difficulty,omitempty"`
	DistanceKm *float32 `json:"distance_km,omitempty"`
	Duration   *string  `json:"duration,omitempty"`
}

// RemoveStop Remove one or more place refs from route and/or stops. Use when replacing a day's overnight — remove the old end before upserting the new one.
type RemoveStop struct {
	Day *int `json:"day,omitempty"`

	// List route, stops, or empty for both
	List *string `json:"list,omitempty"`

	// Place Place id or exact title
	Place *string `json:"place,omitempty"`

	// Places Several place ids or exact titles
	Places *[]string `json:"places,omitempty"`
}

// ReplaceDayRoutesRequest defines model for ReplaceDayRoutesRequest.
type ReplaceDayRoutesRequest struct {
	// Days Day-number string keys (e.g. "7"). Each entry replaces that day's full route. Include title when the overnight/endpoint changes. Typically update day N and day N+1 together. On each route, mark start/end lodging as overnight so the viewer can label Depart.
	Days map[string]struct {
		Notes *string   `json:"notes,omitempty"`
		Route []StopRef `json:"route"`
		Title *string   `json:"title,omitempty"`
	} `json:"days"`

	// Places Optional place catalog upserts (kebab-case ids). New places need top-level title, lat, lon, and type — not under info.
	Places *map[string]PlacePatch `json:"places,omitempty"`
}

// RestoreRequest defines model for RestoreRequest.
type RestoreRequest struct {
	VersionId string `json:"version_id"`
}

// SchemaInfo defines model for SchemaInfo.
type SchemaInfo struct {
	DaysPatchExample *map[string]interface{} `json:"days_patch_example,omitempty"`
	Description      *string                 `json:"description,omitempty"`
	Fields           *map[string]string      `json:"fields,omitempty"`

	// NotesPolicy Human-authored notes usage rule for agents (not enforced)
	NotesPolicy   *string   `json:"notes_policy,omitempty"`
	PatchOps      *[]string `json:"patch_ops,omitempty"`
	SchemaVersion *int      `json:"schema_version,omitempty"`
}

// StopRef defines model for StopRef.
type StopRef struct {
	// MapsUrl Optional per-stop Google Maps URL override for the viewer pin
	MapsUrl *string `json:"maps_url,omitempty"`
	Notes   *string `json:"notes,omitempty"`

	// Place Kebab-case place id from places
	Place string `json:"place"`

	// Type Day-local role for this stop on the route (overrides places.*.type). Travel day: first and last lodging = overnight (never via; never depart — the viewer shows Depart on the morning start). Mid road waypoints = via. Sights = attraction, viewpoint, trailhead, etc.
	Type *string `json:"type,omitempty"`
}

// TripList defines model for TripList.
type TripList struct {
	Trips *[]string `json:"trips,omitempty"`
}

// TripPatch One or more structured ops. Prefer update_day for day narrative and
// places.<id>.info for enrichment. Day calendar dates are derived from
// trip.start + (day − 1) when start is set — do not patch per-day dates.
type TripPatch struct {
	// Days Day-number string keys (e.g. "10") to partial day updates. Prefer update_day for title/notes alone. To change an overnight or reorder a route — especially when the next day's start must change too — prefer replaceDayRoutes. Include title (and notes if the narrative should change) on those days.
	Days      *map[string]DayPatch `json:"days,omitempty"`
	DeleteDay *int                 `json:"delete_day,omitempty"`
	InsertDay *InsertDay           `json:"insert_day,omitempty"`

	// Places Map of kebab-case place id to partial place fields. For a new place, title, lat, lon, and type are required at the top level of that object. Never put title under info — info is structured enrichment only (see PlaceInfo) and is deep-merged.
	Places *map[string]PlacePatch `json:"places,omitempty"`

	// RemoveStop Remove one or more place refs from route and/or stops. Use when replacing a day's overnight — remove the old end before upserting the new one.
	RemoveStop *RemoveStop `json:"remove_stop,omitempty"`

	// SwapDays Exactly two day numbers whose entire day bodies are exchanged (reorder). Do not use for changing an overnight or day endpoint — that needs route edits on the affected days (and the next day's start), not a swap.
	SwapDays *[]int `json:"swap_days,omitempty"`

	// UpdateDay Partial update of one existing day (omit fields to leave unchanged)
	UpdateDay *UpdateDay `json:"update_day,omitempty"`

	// UpsertStop Add or update a stop ref by place id. For restaurants, bars, rental desks, and other mid-day venues ALWAYS use list "stops" (with places.* in the same patch). list "route" is only for updating an existing mid-route via/sight already on the drive — never for new venues (chat rejects that and tells you to retry with list stops). For overnight/endpoint or full route replacement, use changeOvernight or replaceDayRoutes instead. place must be a kebab-case id that exists in places (not a display title).
	UpsertStop *UpsertStop `json:"upsert_stop,omitempty"`
}

// TripSummary defines model for TripSummary.
type TripSummary struct {
	Days          *int    `json:"days,omitempty"`
	Description   *string `json:"description,omitempty"`
	Id            *string `json:"id,omitempty"`
	SchemaVersion *int    `json:"schema_version,omitempty"`
	Start         *string `json:"start,omitempty"`
	Trip          *string `json:"trip,omitempty"`
	VersionId     *string `json:"version_id,omitempty"`
}

// UpdateDay Partial update of one existing day (omit fields to leave unchanged)
type UpdateDay struct {
	Day   int   `json:"day"`
	Ferry *bool `json:"ferry,omitempty"`
	Hike  *bool `json:"hike,omitempty"`

	// Notes Day narrative; set when the user asks to edit notes
	Notes        *string `json:"notes,omitempty"`
	Photo        *string `json:"photo,omitempty"`
	PhotoCaption *string `json:"photo_caption,omitempty"`
	Title        *string `json:"title,omitempty"`
}

// UpsertStop Add or update a stop ref by place id. For restaurants, bars, rental desks, and other mid-day venues ALWAYS use list "stops" (with places.* in the same patch). list "route" is only for updating an existing mid-route via/sight already on the drive — never for new venues (chat rejects that and tells you to retry with list stops). For overnight/endpoint or full route replacement, use changeOvernight or replaceDayRoutes instead. place must be a kebab-case id that exists in places (not a display title).
type UpsertStop struct {
	Day *int `json:"day,omitempty"`

	// List "stops" for mid-day venues/logistics (default choice). "route" only when updating an existing mid-drive via/sight already on that day's route.
	List *string `json:"list,omitempty"`

	// MapsUrl Optional Google Maps URL override on this stop ref
	MapsUrl *string `json:"maps_url,omitempty"`
	Notes   *string `json:"notes,omitempty"`

	// Place Kebab-case place id from places (e.g. greymouth), not a display title
	Place *string `json:"place,omitempty"`
	Type  *string `json:"type,omitempty"`
}

// VersionList defines model for VersionList.
type VersionList struct {
	Id       *string `json:"id,omitempty"`
	Versions *[]struct {
		IsLatest     *bool   `json:"is_latest,omitempty"`
		LastModified *string `json:"last_modified,omitempty"`
		VersionId    *string `json:"version_id,omitempty"`
	} `json:"versions,omitempty"`
}

// CreateTripParams defines parameters for CreateTrip.
type CreateTripParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PatchTripParams defines parameters for PatchTrip.
type PatchTripParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// ReplaceDayRoutesParams defines parameters for ReplaceDayRoutes.
type ReplaceDayRoutesParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// RestoreVersionParams defines parameters for RestoreVersion.
type RestoreVersionParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// GetTripYAMLParams defines parameters for GetTripYAML.
type GetTripYAMLParams struct {
	// Scope day = neighborhood YAML (days N±1 + referenced places).
	// full = entire itinerary. Chat tools default to day when a viewer day is known.
	Scope *GetTripYAMLParamsScope `form:"scope,omitempty" json:"scope,omitempty"`

	// Day Center day for scope=day (chat defaults to the viewer day).
	Day *int `form:"day,omitempty" json:"day,omitempty"`
}

// GetTripYAMLParamsScope defines parameters for GetTripYAML.
type GetTripYAMLParamsScope string

// PutTripYAMLTextBody defines parameters for PutTripYAML.
type PutTripYAMLTextBody = string

// PutTripYAMLParams defines parameters for PutTripYAML.
type PutTripYAMLParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// CreateTripJSONRequestBody defines body for CreateTrip for application/json ContentType.
type CreateTripJSONRequestBody = CreateTripRequest

// PatchTripJSONRequestBody defines body for PatchTrip for application/json ContentType.
type PatchTripJSONRequestBody = TripPatch

// ReplaceDayRoutesJSONRequestBody defines body for ReplaceDayRoutes for application/json ContentType.
type ReplaceDayRoutesJSONRequestBody = ReplaceDayRoutesRequest

// RestoreVersionJSONRequestBody defines body for RestoreVersion for application/json ContentType.
type RestoreVersionJSONRequestBody = RestoreRequest

// PutTripYAMLTextRequestBody defines body for PutTripYAML for text/plain ContentType.
type PutTripYAMLTextRequestBody = PutTripYAMLTextBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetSchema Itinerary schema and version
	// (GET /api/agent/schema)
	GetSchema(w http.ResponseWriter, r *http.Request)
	// ListTrips List itinerary IDs
	// (GET /api/agent/trips)
	ListTrips(w http.ResponseWriter, r *http.Request)
	// CreateTrip Create itinerary
	// (POST /api/agent/trips)
	CreateTrip(w http.ResponseWriter, r *http.Request, params CreateTripParams)
	// GetTrip Compact trip title card (not full routes)
	// (GET /api/agent/trips/{id})
	GetTrip(w http.ResponseWriter, r *http.Request, id string)
	// PatchTrip Patch places info, day narrative, or structure
	// (PATCH /api/agent/trips/{id})
	PatchTrip(w http.ResponseWriter, r *http.Request, id string, params PatchTripParams)
	// ReplaceDayRoutes Replace full day routes (overnight / endpoint changes)
	// (POST /api/agent/trips/{id}/day-routes)
	ReplaceDayRoutes(w http.ResponseWriter, r *http.Request, id string, params ReplaceDayRoutesParams)
	// RestoreVersion Restore a prior YAML version
	// (POST /api/agent/trips/{id}/restore)
	RestoreVersion(w http.ResponseWriter, r *http.Request, id string, params RestoreVersionParams)
	// ListVersions List YAML versions
	// (GET /api/agent/trips/{id}/versions)
	ListVersions(w http.ResponseWriter, r *http.Request, id string)
	// GetVersion Get YAML for a prior version
	// (GET /api/agent/trips/{id}/versions/{version_id})
	GetVersion(w http.ResponseWriter, r *http.Request, id string, versionId string)
	// GetTripYAML Get itinerary YAML (day neighborhood by default in chat)
	// (GET /api/agent/trips/{id}/yaml)
	GetTripYAML(w http.ResponseWriter, r *http.Request, id string, params GetTripYAMLParams)
	// PutTripYAML Replace YAML (raw text body)
	// (PUT /api/agent/trips/{id}/yaml)
	PutTripYAML(w http.ResponseWriter, r *http.Request, id string, params PutTripYAMLParams)
	// Health Liveness
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetSchema operation middleware
func (siw *ServerInterfaceWrapper) GetSchema(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchema(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTrips operation middleware
func (siw *ServerInterfaceWrapper) ListTrips(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrips(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTrip operation middleware
func (siw *ServerInterfaceWrapper) CreateTrip(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTripParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrip(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrip operation middleware
func (siw *ServerInterfaceWrapper) GetTrip(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrip(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchTrip operation middleware
func (siw *ServerInterfaceWrapper) PatchTrip(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchTripParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchTrip(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceDayRoutes operation middleware
func (siw *ServerInterfaceWrapper) ReplaceDayRoutes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ReplaceDayRoutesParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceDayRoutes(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreVersion operation middleware
func (siw *ServerInterfaceWrapper) RestoreVersion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RestoreVersionParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreVersion(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVersions operation middleware
func (siw *ServerInterfaceWrapper) ListVersions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVersions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "version_id" -------------
	var versionId string

	err = runtime.BindStyledParameterWithOptions("simple", "version_id", r.PathValue("version_id"), &versionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r, id, versionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTripYAML operation middleware
func (siw *ServerInterfaceWrapper) GetTripYAML(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTripYAMLParams

	// ------------- Optional query parameter "scope" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "scope", r.URL.Query(), &params.Scope, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "scope"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "scope", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "day" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "day", r.URL.Query(), &params.Day, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "day"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "day", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTripYAML(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutTripYAML operation middleware
func (siw *ServerInterfaceWrapper) PutTripYAML(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutTripYAMLParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutTripYAML(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/schema", wrapper.GetSchema)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/trips", wrapper.ListTrips)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/agent/trips", wrapper.CreateTrip)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/trips/{id}", wrapper.GetTrip)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/agent/trips/{id}", wrapper.PatchTrip)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/agent/trips/{id}/day-routes", wrapper.ReplaceDayRoutes)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/agent/trips/{id}/restore", wrapper.RestoreVersion)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/trips/{id}/versions", wrapper.ListVersions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/trips/{id}/versions/{version_id}", wrapper.GetVersion)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/trips/{id}/yaml", wrapper.GetTripYAML)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/agent/trips/{id}/yaml", wrapper.PutTripYAML)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.Health)

	return m
}
