//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

// CreateTripRequest defines model for CreateTripRequest.
type CreateTripRequest struct {
	Id   string `json:"id"`
	Yaml string `json:"yaml"`
}

// Health defines model for Health.
type Health struct {
	Status *string `json:"status,omitempty"`
}

// MutateResult defines model for MutateResult.
type MutateResult struct {
	BundleError   *string `json:"bundle_error,omitempty"`
	BundleOk      *bool   `json:"bundle_ok,omitempty"`
	Id            *string `json:"id,omitempty"`
	SchemaVersion *int    `json:"schema_version,omitempty"`
	VersionId     *string `json:"version_id,omitempty"`

	// ViewerUrl Signed-in tripmap viewer path /me/trips/{id}/ (Hellō login required)
	ViewerUrl *string `json:"viewer_url,omitempty"`
}

// PlaceInfo Structured enrichment for a place (optional throughout)
type PlaceInfo struct {
	Facilities *struct {
		DrinkingWater *bool `json:"drinking_water,omitempty"`
		Toilets       *bool `json:"toilets,omitempty"`
	} `json:"facilities,omitempty"`
	Highlights *[]string `json:"highlights,omitempty"`
	Links      *[]struct {
		Title *string `json:"title,omitempty"`
		Type  string  `json:"type"`
		Url   string  `json:"url"`
	} `json:"links,omitempty"`
	Logistics *struct {
		BookingRequired *bool   `json:"booking_required,omitempty"`
		Parking         *string `json:"parking,omitempty"`
	} `json:"logistics,omitempty"`
	Source *struct {
		GeneratedAt *string `json:"generated_at,omitempty"`
		GeneratedBy *string `json:"generated_by,omitempty"`
	} `json:"source,omitempty"`
	Stats *struct {
		AscentM    *float32 `json:"ascent_m,omitempty"`
		Difficulty *string  `json:"difficulty,omitempty"`
		DistanceKm *float32 `json:"distance_km,omitempty"`
		Duration   *string  `json:"duration,omitempty"`
	} `json:"stats,omitempty"`
	Warnings *[]string `json:"warnings,omitempty"`
}

// RestoreRequest defines model for RestoreRequest.
type RestoreRequest struct {
	VersionId string `json:"version_id"`
}

// SchemaInfo defines model for SchemaInfo.
type SchemaInfo struct {
	DaysPatchExample *map[string]interface{} `json:"days_patch_example,omitempty"`
	Description      *string                 `json:"description,omitempty"`
	Fields           *map[string]string      `json:"fields,omitempty"`

	// NotesPolicy Human-authored notes usage rule for agents (not enforced)
	NotesPolicy   *string   `json:"notes_policy,omitempty"`
	PatchOps      *[]string `json:"patch_ops,omitempty"`
	SchemaVersion *int      `json:"schema_version,omitempty"`
}

// StopRef defines model for StopRef.
type StopRef struct {
	// MapsUrl Optional per-stop Google Maps URL override for the viewer pin
	MapsUrl *string `json:"maps_url,omitempty"`
	Notes   *string `json:"notes,omitempty"`
	Place   string  `json:"place"`
	Type    *string `json:"type,omitempty"`
}

// TripList defines model for TripList.
type TripList struct {
	Trips *[]string `json:"trips,omitempty"`
}

// TripPatch One or more structured ops. Prefer update_day for day narrative and
// places.<id>.info for enrichment.
type TripPatch struct {
	// Days Legacy map form; prefer update_day
	Days *map[string]struct {
		Ferry *bool `json:"ferry,omitempty"`
		Hike  *bool `json:"hike,omitempty"`

		// Notes Human notes; agents should not modify unless asked
		Notes *string `json:"notes,omitempty"`
		Title *string `json:"title,omitempty"`
	} `json:"days,omitempty"`
	DeleteDay *int `json:"delete_day,omitempty"`
	InsertDay *struct {
		After *int `json:"after,omitempty"`
		Day   *struct {
			Ferry *bool `json:"ferry,omitempty"`
			Hike  *bool `json:"hike,omitempty"`

			// Notes Human-authored; agents should not set unless asked
			Notes *string    `json:"notes,omitempty"`
			Route *[]StopRef `json:"route,omitempty"`
			Stops *[]StopRef `json:"stops,omitempty"`
			Title *string    `json:"title,omitempty"`
		} `json:"day,omitempty"`
	} `json:"insert_day,omitempty"`

	// Places Map of place id to partial place fields (info is deep-merged)
	Places *map[string]struct {
		// Info Structured enrichment for a place (optional throughout)
		Info *PlaceInfo `json:"info,omitempty"`
		Lat  *float32   `json:"lat,omitempty"`
		Lon  *float32   `json:"lon,omitempty"`

		// MapsUrl Google Maps place URL for the viewer pin; when set, overrides lat/lon search
		MapsUrl      *string `json:"maps_url,omitempty"`
		Notes        *string `json:"notes,omitempty"`
		Photo        *string `json:"photo,omitempty"`
		PhotoCaption *string `json:"photo_caption,omitempty"`
		Title        *string `json:"title,omitempty"`
		Type         *string `json:"type,omitempty"`
	} `json:"places,omitempty"`
	RemoveStop *struct {
		Day *int `json:"day,omitempty"`

		// List route, stops, or empty for both
		List  *string `json:"list,omitempty"`
		Place *string `json:"place,omitempty"`
	} `json:"remove_stop,omitempty"`

	// SwapDays Exactly two day numbers to swap
	SwapDays *[]int `json:"swap_days,omitempty"`

	// UpdateDay Partial update of one existing day (omit fields to leave unchanged)
	UpdateDay *struct {
		Day   int   `json:"day"`
		Ferry *bool `json:"ferry,omitempty"`
		Hike  *bool `json:"hike,omitempty"`

		// Notes Day narrative; set when the user asks to edit notes
		Notes        *string `json:"notes,omitempty"`
		Photo        *string `json:"photo,omitempty"`
		PhotoCaption *string `json:"photo_caption,omitempty"`
		Title        *string `json:"title,omitempty"`
	} `json:"update_day,omitempty"`
	UpsertStop *struct {
		Day *int `json:"day,omitempty"`

		// List route or stops
		List *string `json:"list,omitempty"`

		// MapsUrl Optional Google Maps URL override on this stop ref
		MapsUrl *string `json:"maps_url,omitempty"`
		Notes   *string `json:"notes,omitempty"`
		Place   *string `json:"place,omitempty"`
		Type    *string `json:"type,omitempty"`
	} `json:"upsert_stop,omitempty"`
}

// TripSummary defines model for TripSummary.
type TripSummary struct {
	Days          *int    `json:"days,omitempty"`
	Description   *string `json:"description,omitempty"`
	Id            *string `json:"id,omitempty"`
	SchemaVersion *int    `json:"schema_version,omitempty"`
	Start         *string `json:"start,omitempty"`
	Trip          *string `json:"trip,omitempty"`
	VersionId     *string `json:"version_id,omitempty"`
}

// VersionList defines model for VersionList.
type VersionList struct {
	Id       *string `json:"id,omitempty"`
	Versions *[]struct {
		IsLatest     *bool   `json:"is_latest,omitempty"`
		LastModified *string `json:"last_modified,omitempty"`
		VersionId    *string `json:"version_id,omitempty"`
	} `json:"versions,omitempty"`
}

// CreateTripParams defines parameters for CreateTrip.
type CreateTripParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PatchTripParams defines parameters for PatchTrip.
type PatchTripParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// RestoreVersionParams defines parameters for RestoreVersion.
type RestoreVersionParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// PutTripYAMLTextBody defines parameters for PutTripYAML.
type PutTripYAMLTextBody = string

// PutTripYAMLParams defines parameters for PutTripYAML.
type PutTripYAMLParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// CreateTripJSONRequestBody defines body for CreateTrip for application/json ContentType.
type CreateTripJSONRequestBody = CreateTripRequest

// PatchTripJSONRequestBody defines body for PatchTrip for application/json ContentType.
type PatchTripJSONRequestBody = TripPatch

// RestoreVersionJSONRequestBody defines body for RestoreVersion for application/json ContentType.
type RestoreVersionJSONRequestBody = RestoreRequest

// PutTripYAMLTextRequestBody defines body for PutTripYAML for text/plain ContentType.
type PutTripYAMLTextRequestBody = PutTripYAMLTextBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetSchema Itinerary schema and version
	// (GET /api/agent/schema)
	GetSchema(w http.ResponseWriter, r *http.Request)
	// ListTrips List itinerary IDs
	// (GET /api/agent/trips)
	ListTrips(w http.ResponseWriter, r *http.Request)
	// CreateTrip Create itinerary
	// (POST /api/agent/trips)
	CreateTrip(w http.ResponseWriter, r *http.Request, params CreateTripParams)
	// GetTrip Trip summary
	// (GET /api/agent/trips/{id})
	GetTrip(w http.ResponseWriter, r *http.Request, id string)
	// PatchTrip Patch places info, day narrative, or structure
	// (PATCH /api/agent/trips/{id})
	PatchTrip(w http.ResponseWriter, r *http.Request, id string, params PatchTripParams)
	// RestoreVersion Restore a prior YAML version
	// (POST /api/agent/trips/{id}/restore)
	RestoreVersion(w http.ResponseWriter, r *http.Request, id string, params RestoreVersionParams)
	// ListVersions List YAML versions
	// (GET /api/agent/trips/{id}/versions)
	ListVersions(w http.ResponseWriter, r *http.Request, id string)
	// GetVersion Get YAML for a prior version
	// (GET /api/agent/trips/{id}/versions/{version_id})
	GetVersion(w http.ResponseWriter, r *http.Request, id string, versionId string)
	// GetTripYAML Get raw YAML
	// (GET /api/agent/trips/{id}/yaml)
	GetTripYAML(w http.ResponseWriter, r *http.Request, id string)
	// PutTripYAML Replace YAML (raw text body)
	// (PUT /api/agent/trips/{id}/yaml)
	PutTripYAML(w http.ResponseWriter, r *http.Request, id string, params PutTripYAMLParams)
	// Health Liveness
	// (GET /health)
	Health(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetSchema operation middleware
func (siw *ServerInterfaceWrapper) GetSchema(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchema(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTrips operation middleware
func (siw *ServerInterfaceWrapper) ListTrips(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTrips(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTrip operation middleware
func (siw *ServerInterfaceWrapper) CreateTrip(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTripParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTrip(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrip operation middleware
func (siw *ServerInterfaceWrapper) GetTrip(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrip(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchTrip operation middleware
func (siw *ServerInterfaceWrapper) PatchTrip(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PatchTripParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchTrip(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RestoreVersion operation middleware
func (siw *ServerInterfaceWrapper) RestoreVersion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params RestoreVersionParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RestoreVersion(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListVersions operation middleware
func (siw *ServerInterfaceWrapper) ListVersions(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVersions(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVersion operation middleware
func (siw *ServerInterfaceWrapper) GetVersion(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "version_id" -------------
	var versionId string

	err = runtime.BindStyledParameterWithOptions("simple", "version_id", r.PathValue("version_id"), &versionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVersion(w, r, id, versionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTripYAML operation middleware
func (siw *ServerInterfaceWrapper) GetTripYAML(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTripYAML(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutTripYAML operation middleware
func (siw *ServerInterfaceWrapper) PutTripYAML(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params PutTripYAMLParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutTripYAML(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Health operation middleware
func (siw *ServerInterfaceWrapper) Health(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Health(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/schema", wrapper.GetSchema)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/trips", wrapper.ListTrips)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/agent/trips", wrapper.CreateTrip)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/trips/{id}", wrapper.GetTrip)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/api/agent/trips/{id}", wrapper.PatchTrip)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/agent/trips/{id}/restore", wrapper.RestoreVersion)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/trips/{id}/versions", wrapper.ListVersions)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/trips/{id}/versions/{version_id}", wrapper.GetVersion)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/agent/trips/{id}/yaml", wrapper.GetTripYAML)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/api/agent/trips/{id}/yaml", wrapper.PutTripYAML)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.Health)

	return m
}
